new-item $env:userprofile\desktop\DossierA -type d
new-item $env:userprofile\desktop\DossierA\DossierB,$env:userprofile\desktop\DossierA\DossierC -type d
new-item $env:userprofile\desktop\DossierA\FichierA -type f
new-item $env:userprofile\desktop\DossierA\DossierB\DossierD -type d
new-item $env:userprofile\desktop\DossierA\DossierB\FichierB,$env:userprofile\desktop\DossierA\DossierB\FichierC -type f
new-item $env:userprofile\desktop\DossierA\DossierC\FichierD -type f
new-item $env:userprofile\desktop\DossierA\DossierB\DossierD\FichierE -type f
new-item $env:userprofile\desktop\DossierA\DossierB\DossierD\FichierF -type f
new-item $env:userprofile\desktop\DossierA\DossierB\DossierD\FichierG -type f